---
datacenter:
  children:
    routers:
      hosts:
        10.0.0.10
      vars:
        ansible_connection: network_cli
        ansible_network_os: ios
        ansible_user: teste
        ansible_ssh_pass: teste
        ansible_become_password: teste