---
datacenter:
  children:
    routers:
      hosts:
        ip
      vars:
        ansible_connection: network_cli
        ansible_network_os: ce
        ansible_user: username
        ansible_ssh_pass: password
        ansible_become_password: password