---
- name: Cisco Device Automation - Custom Commands
  hosts: all
  gather_facts: yes

  vars:
    cli:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      transport: cli

  tasks:
    - name: Custom Commands
      ce_command:
        commands:
      register: display_output

    - name: Command Output
      debug:
        var: display_output.stdout_lines
