# Generated by Django 4.2.3 on 2024-01-09 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(verbose_name='description')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('inventory_file', models.FileField(upload_to='backend/lib/ansible/inventory/')),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=50)),
                ('add_inventory', models.BooleanField(default=False)),
                ('add_playbook', models.BooleanField(default=False)),
                ('add_template', models.BooleanField(default=False)),
                ('execute_template', models.BooleanField(default=False)),
                ('remove_itens', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(verbose_name='description')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('playbook_file', models.FileField(upload_to='backend/lib/ansible/playbooks/')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('status', models.CharField(choices=[('0', 'Success'), ('1', 'Running'), ('2', 'Failed'), ('3', 'Failed'), ('4', 'Unreachable')], default='0', max_length=1)),
                ('hour', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('output', models.TextField(verbose_name='Output')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('version', models.CharField(max_length=10, verbose_name='Version')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_template', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='backend.inventory')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='backend.playbook')),
                ('tasks', models.ManyToManyField(related_name='task_template', to='backend.task')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('password', models.CharField(max_length=15, verbose_name='Password')),
                ('activity', models.ManyToManyField(related_name='activity_project', to='backend.activity')),
                ('inventories', models.ManyToManyField(related_name='inventory_project', to='backend.inventory')),
                ('key', models.ManyToManyField(related_name='project_key', to='backend.key')),
                ('members', models.ManyToManyField(related_name='members_projects', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
                ('playbooks', models.ManyToManyField(related_name='playbook_project', to='backend.playbook')),
                ('templates', models.ManyToManyField(related_name='template_project', to='backend.template')),
            ],
        ),
    ]
