# Generated by Django 4.2.3 on 2023-12-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_activity_inventory_playbook_task_template_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('0', 'Success'), ('1', 'Running'), ('2', 'Failed'), ('3', 'Failed'), ('4', 'Unreachable')], default='0', max_length=1),
        ),
    ]
