# Generated by Django 4.2.3 on 2023-07-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansiblelog',
            name='host',
            field=models.TextField(verbose_name='Hosts'),
        ),
    ]
