# Generated by Django 4.2.3 on 2023-10-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_hostcustom_device_hostcustom_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostcustom',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='playbookcustom',
            name='tag',
        ),
        migrations.AddField(
            model_name='hostcustom',
            name='switch',
            field=models.TextField(default='None', verbose_name='Switch'),
        ),
        migrations.AddField(
            model_name='playbookcustom',
            name='switch',
            field=models.TextField(default='None', verbose_name='Switch'),
        ),
        migrations.AlterField(
            model_name='hostcustom',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='playbookcustom',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
    ]
