# Generated by Django 4.2.3 on 2023-10-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_hostcustom_tag_remove_playbookcustom_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ansiblelog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ansiblelog',
            name='switch',
        ),
        migrations.AddField(
            model_name='ansiblelog',
            name='data',
            field=models.CharField(default='New DB', max_length=10, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='ansiblelog',
            name='description',
            field=models.TextField(default='New DB', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='ansiblelog',
            name='service',
            field=models.TextField(default='New DB', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='ansiblelog',
            name='host',
            field=models.TextField(default='New DB', verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='ansiblelog',
            name='hour',
            field=models.CharField(default='New DB', max_length=10, verbose_name='Hour'),
        ),
        migrations.AlterField(
            model_name='ansiblelog',
            name='output',
            field=models.TextField(default='New DB', verbose_name='Output'),
        ),
        migrations.AlterField(
            model_name='ansiblelog',
            name='playbook',
            field=models.TextField(default='New DB', verbose_name='Playbook'),
        ),
    ]
