# Generated by Django 4.2.3 on 2023-10-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_ansiblelog_date_remove_ansiblelog_switch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('command', models.TextField(verbose_name='Command')),
                ('switch', models.CharField(choices=[('CW', 'Cisco'), ('HW', 'Huawei')], max_length=2)),
            ],
        ),
    ]
