# Generated by Django 4.2.3 on 2023-10-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_command'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ansiblelog',
            options={},
        ),
        migrations.AlterField(
            model_name='playbookcustom',
            name='switch',
            field=models.CharField(choices=[('CW', 'Cisco'), ('HW', 'Huawei')], max_length=2),
        ),
    ]
