# Generated by Django 4.2.3 on 2023-10-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_hostcustom_switch_alter_hostcustom_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostcustom',
            name='switch',
            field=models.CharField(choices=[('CW', 'Cisco'), ('HW', 'Huawei')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostcustom',
            name='device',
            field=models.TextField(default='Example: 10.0.0.0', verbose_name='Device'),
        ),
    ]
